# Generated by Django 4.2.7 on 2023-11-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no_prefix', models.CharField(blank=True, default='p', max_length=20)),
                ('reg_no_length', models.IntegerField()),
                ('reg_no_start', models.IntegerField(default=1)),
                ('church_logo', models.ImageField(default='passports/default.jpg', upload_to='church')),
                ('church_name', models.CharField(max_length=200)),
                ('created_on', models.DateField()),
            ],
        ),
    ]
