# Generated by Django 5.0.1 on 2024-01-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0002_delete_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('color', models.CharField(max_length=20)),
                ('all_day', models.BooleanField()),
                ('url', models.URLField(blank=True)),
                ('event_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
