# Generated by Django 5.0.1 on 2024-01-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_alter_event_description_alter_event_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='all_day',
            new_name='allDay',
        ),
    ]
