# Generated by Django 5.0.1 on 2024-01-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='passport',
            field=models.ImageField(default='user_default.jfif', upload_to='users'),
        ),
    ]
