# Generated by Django 4.2.7 on 2023-12-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pious_society', '0002_alter_pioussociety_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pioussociety',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled'), ('Probation', 'Probation')], default='Active', max_length=10),
        ),
    ]
