# Generated by Django 4.2.7 on 2023-11-27 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slogan', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_days', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Sunday', max_length=20)),
                ('meeting_days_suff', models.CharField(choices=[('', 'Select one'), ('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], default='', max_length=20)),
                ('meeting_frequency', models.CharField(choices=[('Weekly', 'Weekly'), ('BiWeekly', 'Every two weeks'), ('Monthly', 'Monthly'), ('BiMonthly', 'Every two months'), ('Quarterly', 'Every three months'), ('BiAnnually', 'Every six months'), ('Annually', 'Annually'), ('Biennially', 'Once every 2 years')], default='Monthly', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled'), ('Deleted', 'Deleted')], default='Active', max_length=10)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.station')),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='station',
            field=models.ManyToManyField(related_name='organisations', through='organisation.OrganisationInfo', to='station.station'),
        ),
    ]
