# Generated by Django 4.2.7 on 2023-12-28 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parishioner', '0006_alter_layapostolateinfo_lay_apostolate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minister', models.CharField(max_length=100)),
                ('sponsor', models.CharField(max_length=100)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parishioner.parishioner')),
            ],
        ),
    ]
