# Generated by Django 4.2.7 on 2023-11-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(max_length=14)),
                ('type', models.CharField(choices=[('PP', 'Parish Priest'), ('APP', 'Asst. Parish Priest'), ('PIR', 'Priest in Residence')], default='PP', max_length=3)),
                ('passport', models.ImageField(default='passports/default.jpg', upload_to='passports')),
                ('date_of_birth', models.DateField()),
                ('date_ordained', models.DateField()),
                ('date_resumed', models.DateField()),
                ('date_transfered', models.DateField(blank=True)),
            ],
        ),
    ]
