# Generated by Django 4.2.7 on 2023-12-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priest',
            name='date_transfered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
