# Generated by Django 5.0.1 on 2024-01-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priest', '0002_alter_priest_date_transfered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priest',
            name='passport',
            field=models.ImageField(default='priest_default.jfif', upload_to='priests'),
        ),
    ]
