# Generated by Django 4.2.7 on 2023-11-27 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pious_society', '0001_initial'),
        ('other_group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('society', '0001_initial'),
        ('station', '0001_initial'),
        ('lay_apostolate', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayApostolateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled'), ('Deleted', 'Deleted')], default='Active', max_length=10)),
                ('lay_apostolate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lay_apostolate.layapostolate')),
            ],
        ),
        migrations.CreateModel(
            name='OtherGroupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled'), ('Deleted', 'Deleted')], default='Active', max_length=10)),
                ('other_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other_group.othergroup')),
            ],
        ),
        migrations.CreateModel(
            name='Parishioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('reg_no', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=14)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('residential_address', models.CharField(max_length=200)),
                ('home_address', models.CharField(blank=True, max_length=200)),
                ('office_address', models.CharField(blank=True, max_length=200)),
                ('diocese_of_origin', models.CharField(max_length=100)),
                ('parish_of_origin', models.CharField(max_length=100)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('lga_of_origin', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('passport', models.ImageField(default='passports/default.jpg', upload_to='passports')),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced')], default='Single', max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('spouse_name', models.CharField(blank=True, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled'), ('Deleted', 'Deleted')], default='Active', max_length=10)),
                ('baptised', models.BooleanField()),
                ('communicant', models.BooleanField()),
                ('confirmed', models.BooleanField()),
                ('wedded', models.BooleanField()),
                ('charisma', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parishioners_created', to=settings.AUTH_USER_MODEL)),
                ('lay_apostolate', models.ManyToManyField(blank=True, related_name='members', through='parishioner.LayApostolateInfo', to='lay_apostolate.layapostolate')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parishioners_modified', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organisation.organisationinfo')),
                ('other_group', models.ManyToManyField(blank=True, related_name='members', through='parishioner.OtherGroupInfo', to='other_group.othergroup')),
            ],
        ),
        migrations.CreateModel(
            name='PiousSocietyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled'), ('Deleted', 'Deleted')], default='Active', max_length=10)),
                ('parishioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parishioner.parishioner')),
                ('pious_society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pious_society.pioussociety')),
            ],
        ),
        migrations.AddField(
            model_name='parishioner',
            name='pious_society',
            field=models.ManyToManyField(blank=True, related_name='members', through='parishioner.PiousSocietyInfo', to='pious_society.pioussociety'),
        ),
        migrations.AddField(
            model_name='parishioner',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='station.station'),
        ),
        migrations.AddField(
            model_name='parishioner',
            name='working_society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='society.workingsociety'),
        ),
        migrations.AddField(
            model_name='othergroupinfo',
            name='parishioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parishioner.parishioner'),
        ),
        migrations.AddField(
            model_name='layapostolateinfo',
            name='parishioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parishioner.parishioner'),
        ),
    ]
