# Generated by Django 4.2.7 on 2023-11-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parishioner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishioner',
            name='organisation_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled')], default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='parishioner',
            name='station_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled')], default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='parishioner',
            name='working_society_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='layapostolateinfo',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='othergroupinfo',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='parishioner',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='pioussocietyinfo',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled')], default='Active', max_length=10),
        ),
    ]
