# Generated by Django 4.2.7 on 2023-12-06 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parishioner', '0002_parishioner_organisation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishioner',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parishioners_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parishioner',
            name='deleted_on',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='DeathDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('died_on', models.DateField()),
                ('buried_on', models.DateField(blank=True, null=True)),
                ('buried_by', models.CharField(blank=True, max_length=200)),
                ('buried_at', models.CharField(blank=True, max_length=400)),
                ('parishioner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parishioner.parishioner')),
            ],
        ),
    ]
