# Generated by Django 4.2.7 on 2023-12-06 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parishioner', '0003_parishioner_deleted_by_parishioner_deleted_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeathDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('died_on', models.DateField()),
                ('buried_on', models.DateField(blank=True, null=True)),
                ('buried_by', models.CharField(blank=True, max_length=200)),
                ('buried_at', models.CharField(blank=True, max_length=400)),
                ('parishioner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='death_details', to='parishioner.parishioner')),
            ],
        ),
        migrations.DeleteModel(
            name='DeathDetails',
        ),
    ]
