# Generated by Django 4.2.7 on 2023-12-07 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parishioner', '0004_deathdetail_delete_deathdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deathdetail',
            name='parishioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='death_detail', to='parishioner.parishioner'),
        ),
    ]
