# Generated by Django 4.2.7 on 2023-12-15 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pious_society', '0003_alter_pioussociety_status'),
        ('lay_apostolate', '0003_alter_layapostolate_status'),
        ('other_group', '0003_alter_othergroup_status'),
        ('parishioner', '0005_alter_deathdetail_parishioner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layapostolateinfo',
            name='lay_apostolate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parishioner_status', to='lay_apostolate.layapostolate'),
        ),
        migrations.AlterField(
            model_name='layapostolateinfo',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled'), ('Probation', 'Probation')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='othergroupinfo',
            name='other_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parishioner_status', to='other_group.othergroup'),
        ),
        migrations.AlterField(
            model_name='othergroupinfo',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled'), ('Probation', 'Probation')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='parishioner',
            name='organisation_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled'), ('Probation', 'Probation')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='parishioner',
            name='station_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled'), ('Probation', 'Probation')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='parishioner',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled'), ('Probation', 'Probation')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='parishioner',
            name='working_society_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled'), ('Probation', 'Probation')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='pioussocietyinfo',
            name='pious_society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parishioner_status', to='pious_society.pioussociety'),
        ),
        migrations.AlterField(
            model_name='pioussocietyinfo',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled'), ('Probation', 'Probation')], default='Active', max_length=10),
        ),
    ]
