# Generated by Django 4.2.7 on 2023-11-27 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parishioner', '0001_initial'),
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled'), ('Deleted', 'Deleted')], default='Active', max_length=10)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='station.station')),
            ],
        ),
        migrations.CreateModel(
            name='CouncilHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('', 'Select one'), ('President', 'President'), ('Chairman', 'Chairman'), ('VP', 'Vice President'), ('VP1', 'Vice President 1'), ('VP2', 'Vice President 2'), ('VC', 'Vice Chairman'), ('Sect.', 'Secretary'), ('Asst. Sect.', 'Assistant Secretary'), ('Provost1', 'Provost 1'), ('Provost2', 'Provost 2'), ('PRO1', 'PRO 1'), ('PRO2', 'PRO 2'), ('Treasurer', 'Treasurer'), ('Fin. Sect.', 'Financial Secretary'), ('Chaplain', 'Chaplain')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled'), ('Deleted', 'Deleted')], default='Active', max_length=10)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council.council')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='parishioner.parishioner')),
            ],
        ),
    ]
