# Generated by Django 4.2.7 on 2023-12-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_alter_station_status'),
        ('council', '0003_alter_council_status_alter_councilhead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='council',
            name='station',
        ),
        migrations.CreateModel(
            name='StationCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled'), ('Probation', 'Probation')], default='Active', max_length=10)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='council.council')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='councils', to='station.station')),
            ],
        ),
        migrations.AddField(
            model_name='council',
            name='station',
            field=models.ManyToManyField(through='council.StationCouncil', to='station.station'),
        ),
        migrations.AlterField(
            model_name='councilhead',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='council.stationcouncil'),
        ),
    ]
