# Generated by Django 4.2.7 on 2023-12-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='reg_no_length',
            field=models.IntegerField(default=5),
        ),
    ]
