# Generated by Django 4.2.7 on 2024-01-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_alter_setting_reg_no_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='baptism_reg_no_length',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='setting',
            name='baptism_reg_no_prefix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='baptism_reg_no_start',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='setting',
            name='church_address',
            field=models.CharField(default='32 Anwana Esin, Oron', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='church_saint_logo',
            field=models.ImageField(default='passports/default.jpg', upload_to='church'),
        ),
        migrations.AddField(
            model_name='setting',
            name='communion_reg_no_length',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='setting',
            name='communion_reg_no_prefix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='communion_reg_no_start',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='setting',
            name='confirmation_reg_no_length',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='setting',
            name='confirmation_reg_no_prefix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='confirmation_reg_no_start',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='setting',
            name='email_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setting',
            name='email_port',
            field=models.IntegerField(blank=True, default='582'),
        ),
        migrations.AddField(
            model_name='setting',
            name='email_server',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setting',
            name='email_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setting',
            name='matrimony_reg_no_length',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='setting',
            name='matrimony_reg_no_prefix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='matrimony_reg_no_start',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='setting',
            name='reg_no_prefix',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
