# Generated by Django 5.0.1 on 2024-01-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_alter_setting_church_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='email_port',
            field=models.IntegerField(default=582),
        ),
        migrations.AlterField(
            model_name='setting',
            name='matrimony_reg_no_start',
            field=models.IntegerField(default=1),
        ),
    ]
