# Generated by Django 4.2.7 on 2023-12-28 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parishioner', '0006_alter_layapostolateinfo_lay_apostolate_and_more'),
        ('priest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_parent', models.CharField(max_length=100)),
                ('bride_village', models.CharField(max_length=100)),
                ('groom_parent', models.CharField(max_length=100)),
                ('groom_village', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('sponsor', models.CharField(max_length=100)),
                ('sponsor_address', models.CharField(max_length=100)),
                ('bride', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='brides', to='parishioner.parishioner')),
                ('groom', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grooms', to='parishioner.parishioner')),
                ('minister', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='priest.priest')),
            ],
        ),
    ]
