# Generated by Django 4.2.7 on 2023-11-27 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('date_created', models.DateField(default=datetime.datetime.today)),
                ('picture', models.ImageField(default='station_pictures/default.jpg', upload_to='station_pictures')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled'), ('Deleted', 'Deleted')], default='Active', max_length=10)),
            ],
        ),
    ]
