# Generated by Django 4.2.7 on 2023-12-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_alter_station_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Domiciled', 'Domiciled'), ('Probation', 'Probation')], default='Active', max_length=10),
        ),
    ]
