# Generated by Django 5.0.1 on 2024-01-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_alter_station_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='picture',
            field=models.ImageField(default='church_default.jfif', upload_to='station_pictures'),
        ),
    ]
